[package]
name = "interop_client"
version = "0.1.0"
authors = ["Konrad Kohbrok <konrad.kohbrok@datashrine.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openmls = { path = "../" }
tonic = "0.3"
prost = "0.6"
tokio = { version = "1.2", features = ["macros", "rt-multi-thread", "net"] }
clap = "3.0.0-beta.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"

[build-dependencies]
tonic-build = "0.3"
