name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: openmls

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # (Cross-)Compile everything except iOS sim on linux
        os:
          - ubuntu-latest
        arch:
          # Windows
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          # macOS
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          # Linux
          - x86-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          # Android
          - aarch64-linux-android
          # iOS
          - aarch64-apple-ios
          # WASM
          - wasm32-unknown-unknown
        include:
          # Compile iOS sim on macOS
          - os: macos-latest
            arch: aarch64-apple-ios-sim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.arch }}
      - name: Build Release
        run: cargo build --release --verbose --target ${{ matrix.arch }}
      - name: Build Test
        run: cargo test --no-run --verbose --target ${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}_test_artifact
          path: |
            target/${{ matrix.arch }}/debug/deps/openmls-*
            test_vectors/
            !target/${{ matrix.arch }}/debug/deps/openmls-*.d
