name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: openmls

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        arch:
          # Windows
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          # macOS
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          # Linux
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          # Android
          - aarch64-linux-android
          # iOS
          - aarch64-apple-ios
          # WASM
          - wasm32-unknown-unknown
        include:
          # Compile iOS sim on macOS
          - os: macos-latest
            arch: aarch64-apple-ios-sim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # Install the required target
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.arch }}
          components: rustfmt, clippy
      - name: Build debug
        run: cargo build --verbose --target ${{ matrix.arch }}
      - name: Build release
        run: cargo build --release --verbose --target ${{ matrix.arch }}
